# Generated by Django 4.1.5 on 2023-01-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=255)),
                ("modelo", models.CharField(max_length=255)),
                ("año", models.IntegerField()),
                ("patente", models.CharField(max_length=255)),
                ("nombre_vendedor", models.CharField(max_length=255)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.CharField(max_length=255)),
                ("ciudad", models.CharField(max_length=255)),
                ("estado", models.CharField(max_length=255)),
                ("pais", models.CharField(max_length=255)),
                ("telefono", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comprador_nombre", models.CharField(max_length=255)),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField()),
                (
                    "auto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="autosApp.auto"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="auto",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autosApp.sucursal"
            ),
        ),
    ]
